### ISSUE TITLE
AttributeError: 'Smartmeter' object has no attribute 'tages_verbrauch'

### ISSUE THREAD

**Issue by Constipated-Monk** [DarwinsBuddy/WienerNetzeSmartmeter#199]
Servus,

ich habe auf 1.4 geupdated und meine Entity und Zählerstand neu eingerichtet. Installiert wurde nur eine Entity mit dem Namen meiner Zählernummer_statistics (früher war das noch anders benamt) 
Dazu kommt beim debug logging dieser Error von oben
`AttributeError: 'Smartmeter' object has no attribute 'tages_verbrauch'`

Am Smartmeter und Wien Energie Dashboard ist Viertelstundentracking verfügbar. Das Attribut in der Entity gibt es aber tatsächlich nicht. 
Weiß nicht mehr weiter.

**Comment by simmac** [comment]
yep, same hier. Bei mir ist aber nicht mal statistics da.

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:573
Integration: Sensor (documentation, issues)
First occurred: November 25, 2023 at 12:10:02 PM (1 occurrences)
Last logged: November 25, 2023 at 12:10:02 PM

wnsm: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/live_sensor.py", line 62, in async_update
    yesterdays_consumption = await self.get_daily_consumption(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/live_sensor.py", line 28, in get_daily_consumption
    smartmeter.tages_verbrauch, date, self.zaehlpunkt
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Smartmeter' object has no attribute 'tages_verbrauch'```

Außerdem:

```Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:573
Integration: Sensor (documentation, issues)
First occurred: November 25, 2023 at 12:09:59 PM (1 occurrences)
Last logged: November 25, 2023 at 12:09:59 PM

wnsm: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 957, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/statistics_sensor.py", line 126, in async_update
    await self._import_historical_data(smartmeter)
  File "/config/custom_components/wnsm/statistics_sensor.py", line 140, in _import_historical_data
    recording = await self.get_historic_data(smartmeter)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 131, in get_historic_data
    response = await self.hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 406, in historical_data
    raise SmartmeterQueryError("Returned data does not match given zaehlpunkt!")
custom_components.wnsm.api.errors.SmartmeterQueryError: Returned data does not match given zaehlpunkt!```

**Comment by Kuschla** [comment]
HI, I've noted the same on my installation. 
All _staticstics sensors seem to have lost data and are not available anymore.

**Comment by reox** [comment]
@Constipated-Monk see also #204

**Comment by yetisbey** [comment]
> Hi DarwinsBuddy, updated to 1.41 a few days ago. Ever since then, there is no update on the engergy dashboard nor on the entity itself.

Hi, 
same here. 
regards.
