### ISSUE TITLE
Energy dashboard doesn't show data

### ISSUE THREAD

**Issue by logock** [DarwinsBuddy/WienerNetzeSmartmeter#2]
Could you please provide more information on how the energy dashboard has to be configured so that you can see the daily usage? After adding the integration via HACS, I am unable to get any meaningful data from the entity besides the total usage `meterReadings:value` and hence I assume the energy dashboard won't show anything either.

I checked my /welcome api result and it does show data in `consumptionYesterday` and `consumptionDayBeforeYesterday` so the issue must be with the integration itself?

**Comment by DarwinsBuddy** [comment]
right now, only the `meterReadings` are provided in form of a `total_increasing` `sensor` https://developers.home-assistant.io/blog/2021/08/16/state_class_total/

as the `meterReadings` will be available every day via the API, the sensor's state will increase and the energy dashboard (provided that you added the sensor there) should automatically calculate and present the delta.
Since the API is the bottleneck here and the data is not available in real-time (and even `consumptionYesterday`/`consumptionDayBeforeYesterday` are not reliable even, since often data is missing and has to be extrapolated) there is still a bit one can improve in that integration, though there are hard limits set by the API not able to overcome otherwise.

If the issue persists, please add some logs and/or screenshots.

PRs are also welcome if you want to improve the integration :)

**Comment by logock** [comment]
Unfortunately, the energy dashboard keeps showing 0kWh even though I have added the sensor.

**Comment by logock** [comment]
```Logger: homeassistant.helpers.entity
Source: custom_components/wnsm/api/client.py:55
Integration: WienerNetzeSmartmeter (documentation, issues)
First occurred: September 6, 2022 at 15:28:58 (1 occurrences)
Last logged: September 6, 2022 at 15:28:58

Update for sensor.at################ fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/config/custom_components/wnsm/sensor.py", line 163, in async_update
    await self.hass.async_add_executor_job(smartmeter.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wnsm/api/client.py", line 55, in login
    result = self.session.post(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by DarwinsBuddy** [comment]
Seems like I forgot some error handling. Added it, but unfortunately the cause of this error, I cannot resolve. It seems that the remote hangs up on you. Are you sure the device hosting Home Assistant has a stable internet connection and is able to access the smartmeter api?
