### ISSUE TITLE
v1.4.2: The following integrations and platforms could not be set up:  wnsm.sensor

### ISSUE THREAD

**Issue by Kuschla** [DarwinsBuddy/WienerNetzeSmartmeter#210]
I get the below error:

`2024-01-13 16:32:19.677 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.wnsm.sensor
2024-01-13 16:32:19.701 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'wnsm.sensor': Platform not found (Exception importing custom_components.wnsm.sensor).`

**Comment by akeck** [comment]
More Info:

2024-01-13 15:27:54.052 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.wnsm.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/wnsm/sensor.py", line 26, in <module>
    from .statistics_sensor import StatisticsSensor
  File "/config/custom_components/wnsm/statistics_sensor.py", line 7, in <module>
    from .base_sensor import BaseSensor
  File "/config/custom_components/wnsm/base_sensor.py", line 31, in <module>
    class BaseSensor(SensorEntity, ABC):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_state_class in subclass
2024-01-13 15:27:54.055 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'wnsm.sensor': Platform not found (Exception importing custom_components.wnsm.sensor).
