### ISSUE TITLE
Startup time of WienerNetzeSmartmeter

### ISSUE THREAD

**Issue by acdcnow** [DarwinsBuddy/WienerNetzeSmartmeter#238]
Hi Dev team,

is there a way to improve the startup time of this addin.
According to the Integration startup time the integration needs 10 time more then the next integration item which is Zigbee in my case.

WienerNetzeSmartmeter 121.18 sec
Zigbee 12.30 sec

Is there a technical need for this long runtime or can that be get done to a standard value which is 3-8 sec in my case.

according to the debug log I can just see one issue
2024-06-26 08:21:00.111 ERROR (MainThread) [custom_components.wnsm.statistics_sensor] Error retrieving data from smart meter api - Error: Cannot access daily consumption: {'Exception': 'API Gateway 10.15 encountered an error. Error Message:  Downtime exception: Read timed out. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - /messdaten/{kundennummer}/{zaehlpunkt}/verbrauch, Invocation Time:6:21:00 AM, Date:Jun 26, 2024,  Client IP - XXXX, User - Default and Application:WN_SMART_METER_PORTAL_API_B2C'}
Traceback (most recent call last):
  File "/config/custom_components/wnsm/statistics_sensor.py", line 129, in async_update
    await self._import_statistics(smartmeter, start, _sum)
  File "/config/custom_components/wnsm/statistics_sensor.py", line 261, in _import_statistics
    consumption = await self.get_consumption(smartmeter, start)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 124, in get_consumption
    raise RuntimeError(f"Cannot access daily consumption: {response}")

Maybe after 28.june any adoption is needs as well:
Damit Sie auch künftig unsere Services in gewohnter Qualität nutzen können, führen wir von 28. - 30. Juni 2024 wichtige System-Updates durch. Die Smart Meter-Webportale stehen Ihnen weiterhin zur Verfügung. Für diesen Zeitraum werden vorübergehend keine neuen Daten angezeigt. Nach dem Systemupdate werden alle Daten nachgeladen und stehen Ihnen wie gewohnt zur Verfügung. Wir danken für Ihr Verständnis.

**Comment by reox** [comment]
> Read timed out

The problem is that the API gives you a timeout. Thus, you have waited 60s for that error message...

**Comment by DarwinsBuddy** [comment]
Due to the downstream dependency, there's nothing we can do unfortunately, than wait for it to respond again.
