### ISSUE TITLE
No Data after Update

### ISSUE THREAD

**Issue by ph0xyz** [DarwinsBuddy/WienerNetzeSmartmeter#267]
Hey, 
after yesterdays update to Version 1.5.3 no Data whatsoever is Recieved. No error message, nothing in the logs (at first glance). Message is just: "Unbekannt"
As soon as i roll back to 1.5.2 everything is fine.

Couldn't find the time yet to dig deeper, so no hints as to where the data could get lost. API queries seem to be working.

**Comment by DarwinsBuddy** [comment]
strange. I tested this before

@tschoerk do you have any idea?

**Comment by ryanbrown-at** [comment]
I use two zählpunkte and completely reinstalled the plugin because in the previous versions only one zählpunkt was working. But now (1.5.3) there is only one empty statistic entity of the consumption meter. How can i help with a log file?

**Comment by ryanbrown-at** [comment]
Yes there is correct and actual data in the Wienenergie Webportal.
I'll try one more fresh install. What do you reccomend, config via Integration or add manual the both zählpunkte in config and secrets?

**Comment by tschoerk** [comment]
Ok that's good.
I'd recommend config via integration. Makes troubleshooting, removing and readding easier than having to edit the .yaml every time.

**Comment by ryanbrown-at** [comment]
Unfortunately there was no success. Adding the Integration only produces one empty sensor.

![Screenshot_20241029_144724_Home Assistant](https://github.com/user-attachments/assets/b80b6dd4-31cb-41d1-bc6b-733564210757)

**Comment by ryanbrown-at** [comment]
![Screenshot_20241029_145914_FX](https://github.com/user-attachments/assets/e5cb24d6-b5d6-4000-abd4-3dca60f2103c)

What logfile do you need for a further analysis?

**Comment by tschoerk** [comment]
You got a returned data does not match given zaehlpunkt error, which is often hard to pinpoint the exact problem. I have only seen it with having duplicate/inactive zaehlpunkte in the smart meter portal, but it could potentially be a lot of things.

Do you have some inactive zaehlpunkte or multiple adresses or multiple contracts in your smart meter portal?
[https://smartmeter-web.wienernetze.at/anlagen-und-vertraege/anlagendaten](https://smartmeter-web.wienernetze.at/anlagen-und-vertraege/anlagendaten)
[https://smartmeter-web.wienernetze.at/anlagen-und-vertraege/vertragsverbindungen](https://smartmeter-web.wienernetze.at/anlagen-und-vertraege/vertragsverbindungen)

**Comment by ryanbrown-at** [comment]
Yes, i have multiple contracts (Kundennummern) one for "Verbrauch" and one for "Einspeisung" (PV).

**Comment by tschoerk** [comment]
Thanks for all the information. Since I don't have multiple contracts, it took some time to figure it out, but I think I got it.

The function [get_zaehlpunkt()](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blob/ae19f4ba1557406158b3691518e4f3f8890983e2/custom_components/wnsm/api/client.py#L235) in /api/client.py is the problem, especially the following lines:
https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blob/ae19f4ba1557406158b3691518e4f3f8890983e2/custom_components/wnsm/api/client.py#L243-L249

When adding or updating a sensor, the zaehlpunkt is checked with the get_zaehlpunkt function. The problem is that the variable for the array, which has the zaehlpunkt details in them (line 244), has the same name as the zaehlpunkt itself (line 247).
So when having multiple contracts/customerIds it loops through multiple contracts and the correct zaehlpunkt is overwritten by the zaehlpunkt details, which is now an empty array, since both have the same name. Now an empty array is returned and all API requests are done with an empty array and throw errors all around.

To fix the error try to make the changes in my branch, which you can see [here](https://github.com/tschoerk/WienerNetzeSmartmeter/commit/21c30b666dbd16cb976e0efb743d233eaaa87746)

Let me know if this fixes the issue, then I'll open a PR.

**Comment by ryanbrown-at** [comment]
![Screenshot_20241031_224152_Home Assistant](https://github.com/user-attachments/assets/18ea2d20-26ad-4952-bfce-33e9e6893a1b)

It worked partly, the statistic sensor ist now there for both but the history ist just there for the "Einspeisung".
Thanks!

**Comment by wtaferner** [comment]
I had a similar issue (three customers, only two active meter points) and your not yet proposed bugfix resolved it. 
Thank you 👍🏼

**Comment by tschoerk** [comment]
> ![Screenshot_20241031_224152_Home Assistant](https://private-user-images.githubusercontent.com/101002618/382123712-18ea2d20-26ad-4952-bfce-33e9e6893a1b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NjUxNzcsIm5iZiI6MTczMDY2NDg3NywicGF0aCI6Ii8xMDEwMDI2MTgvMzgyMTIzNzEyLTE4ZWEyZDIwLTI2YWQtNDk1Mi1iZmNlLTMzZTllNjg5M2ExYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QyMDE0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Mjc1YjA3YmRkYjNkM2MzNzViODdmZjhmZWJjZTA0MmQ0ZjBkMjhlMGVlYzAxYzBhZDZiY2ExZWVlMGI0YmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JhSIleyli66o3gJUQ8mKHnNG07UUwEgcyOKJ9yMFALM)
> 
> It worked partly, the statistic sensor ist now there for both but the history ist just there for the "Einspeisung". Thanks!

Can you post the log? Follow the steps in the faq #19 under General Troubleshooting to acquire a log regarding this integration. Probably a second bug involved somewhere.

**Comment by ryanbrown-at** [comment]
In the Logs i can find the following lines:

`2024-11-05 18:39:41.805 ERROR (MainThread) [custom_components.wnsm.statistics_sensor] Error retrieving data from smart meter api - Error: Cannot access daily consumption: {'Exception': 'API Gateway 10.15 encountered an error. Error Message:  Unauthorized application request. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - /messdaten/{kundennummer}/{zaehlpunkt}/verbrauch, Invocation Time:5:39:41 PM, Date:Nov 5, 2024,  Client IP - x.x.x.x (removed), User - Default and Application:WN_SMART_METER_PORTAL_API_B2C'}
Traceback (most recent call last):
  File "/config/custom_components/wnsm/statistics_sensor.py", line 129, in async_update
    await self._import_statistics(smartmeter, start, _sum)
  File "/config/custom_components/wnsm/statistics_sensor.py", line 261, in _import_statistics
    consumption = await self.get_consumption(smartmeter, start)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 125, in get_consumption
    raise RuntimeError(f"Cannot access daily consumption: {response}")
RuntimeError: Cannot access daily consumption: {'Exception': 'API Gateway 10.15 encountered an error. Error Message:  Unauthorized application request. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - /messdaten/{kundennummer}/{zaehlpunkt}/verbrauch, Invocation Time:5:39:41 PM, Date:Nov 5, 2024,  Client IP - x.x.x.x (removed), User - Default and Application:WN_SMART_METER_PORTAL_API_B2C'}`

The full log is nearly 2 Megabytes big, should i upload it? I have to anonymize it first because all the personal data is in there as reply of the api call (including both zählpunkte).

**Comment by tschoerk** [comment]
The error here is for the statistics sensor and not like I assued the live sensor and seems like the API has some problems, but again if it's only for you there are probably some bugs in the code. You could send me the logs per mail (see my profile), so I get the full picture. Remove at least names, adress, but leave the last couple of digits of zaehlpunkt and customer ids, so I can figure out which zaehlpunkt/customer id is throwing which error.

**Comment by ryanbrown-at** [comment]
I have sent you an email with the requested log file.
Thanks!

**Comment by tschoerk** [comment]
> I have sent you an email with the requested log file. Thanks!

Thanks for the logs. Most errors are from the statistics sensor, which is due to an API change (see #268), but you have indeed an interesting error in your bezug zaehlunkt. You return multiple zaehlwerke with different obisCodes, which I have never seen:
```
API Response: {
  "zaehlwerke": [
    {
      "obisCode": "1-1:1.8.1",
      "einheit": "WH",
      "messwerte": []
    },
    {
      "obisCode": "1-1:1.8.2",
      "einheit": "WH",
      "messwerte": []
    },
    {
      "obisCode": "1-1:1.9.0",
      "einheit": "WH",
      "messwerte": []
    }
  ],
  "zaehlpunkt": "AT0010000000000000000000000000BEZ"
}
```

Anyway the return data is actually checked if there's only one OBIS code, because otherwise it could mess with the data and it throws an error. Furthermore all zaehlwerke are empty, so there's not data anyway.

So please do the following to check how to get proper meter readings in your case:
1. Go to https://smartmeter-web.wienernetze.at/verbrauchsdaten/zaehlerdaten
2. Press F12 to bring up the dev tools
3. Click the Tab "Network Analysis"
4. Filter only "XHR"
5. Select your bezugs Zaehlpunkt in the dropdown
6. Refresh the page if needed
7. Look for a GET call to messwerte?datumVon=2021-11-10&datumBis=2024-11-11&wertetyp=METER_READ
8. Click on it and the on "Response" to see which data it returned
9. Right-click copy all
10. Post it here or send it per mail again (there's one occurence of the zaehlpunkt you would need to remove, the rest is just data)

**Comment by ryanbrown-at** [comment]
[log.txt](https://github.com/user-attachments/files/17709291/log.txt)

Just tried, i hope this is the correct Log?

**Comment by tschoerk** [comment]
Yes,. thank you. I will open a new issue for this specifically, since we have two different bugs in your case.
