### ISSUE TITLE
Cannot access daily consumption

### ISSUE THREAD

**Issue by TheRealVira** [DarwinsBuddy/WienerNetzeSmartmeter#269]
Statistic entities are broken:

```
Logger: custom_components.wnsm.statistics_sensor
Source: custom_components/wnsm/statistics_sensor.py:129
integration: WienerNetzeSmartmeter (documentation, issues)
First occurred: 10:02:04 (1 occurrences)
Last logged: 10:02:04

Error retrieving data from smart meter api - Error: Cannot access daily consumption: {'Exception': 'API Gateway 10.15 encountered an error. Error Message: Resource /messdaten/xxx/xxx/verbrauch not found. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - /messdaten/{kundennummer}/{zaehlpunkt}/verbrauch, Invocation Time:9:02:04 AM, Date:Nov 8, 2024, Client IP - xxx, User - Default and Application:null'}
Traceback (most recent call last):
  File "/config/custom_components/wnsm/statistics_sensor.py", line 129, in async_update
    await self._import_statistics(smartmeter, start, _sum)
  File "/config/custom_components/wnsm/statistics_sensor.py", line 261, in _import_statistics
    consumption = await self.get_consumption(smartmeter, start)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 125, in get_consumption
    raise RuntimeError(f"Cannot access daily consumption: {response}")
RuntimeError: Cannot access daily consumption: {'Exception': 'API Gateway 10.15 encountered an error. Error Message: Resource /messdaten/xxx/xxx/verbrauch not found. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - /messdaten/{kundennummer}/{zaehlpunkt}/verbrauch, Invocation Time:9:02:04 AM, Date:Nov 8, 2024,  Client IP - xxx, User - Default and Application:null'}
```

**Comment by reox** [comment]
yep :( It looks like the API has changed once again. See #268

**Comment by TheRealVira** [comment]
Täglich grüßt das Murmeltier… they should really have some sort of „release news“ channel for breaking changes 😄
