### ISSUE TITLE
Second SM

### ISSUE THREAD

**Issue by elmartinoAT** [DarwinsBuddy/WienerNetzeSmartmeter#279]
I have 2 smartmeter in the webportal,
the second one and _statistics of the second one is shown as 'not available' in HA

Logger: custom_components.wnsm.statistics_sensor
Quelle: custom_components/wnsm/statistics_sensor.py:121
Integration: WienerNetzeSmartmeter (Dokumentation, Probleme)
Erstmals aufgetreten: 19:24:32 (2 Vorkommnisse)
Zuletzt protokolliert: 19:24:32

Starting import of historical data. This might take some time.

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.wnsm.live_sensor
Quelle: custom_components/wnsm/live_sensor.py:36
Integration: WienerNetzeSmartmeter (Dokumentation, Probleme)
Erstmals aufgetreten: 19:24:32 (1 Vorkommnisse)
Zuletzt protokolliert: 19:24:32

Error retrieving data from smart meter api - Error:
Traceback (most recent call last):
  File "/config/custom_components/wnsm/live_sensor.py", line 36, in async_update
    meter_readings = await self.get_meter_reading_from_historic_data(smartmeter,reading_date)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 155, in get_meter_reading_from_historic_data
    response = await self.hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 454, in historical_data
    customer_id, zaehlpunkt, anlagetype = self.get_zaehlpunkt(zaehlpunktnummer)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 250, in get_zaehlpunkt
    return customer_id, zp, const.AnlageType.from_str(anlagetype)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/constants.py", line 72, in from_str
    raise NotImplementedError
NotImplementedError

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.wnsm.statistics_sensor
Quelle: custom_components/wnsm/statistics_sensor.py:122
Integration: WienerNetzeSmartmeter (Dokumentation, Probleme)
Erstmals aufgetreten: 19:24:33 (1 Vorkommnisse)
Zuletzt protokolliert: 19:24:33

Error retrieving data from smart meter api - Error:
Traceback (most recent call last):
  File "/config/custom_components/wnsm/statistics_sensor.py", line 122, in async_update
    await self._initial_import_statistics(smartmeter)
  File "/config/custom_components/wnsm/statistics_sensor.py", line 158, in _initial_import_statistics
    return await self._import_statistics(smartmeter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/statistics_sensor.py", line 177, in _import_statistics
    bewegungsdaten = await self.get_bewegungsdaten(smartmeter, start, end)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 169, in get_bewegungsdaten
    response = await self.hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 510, in bewegungsdaten
    customer_id, zaehlpunkt, anlagetype = self.get_zaehlpunkt(zaehlpunktnummer)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 250, in get_zaehlpunkt
    return customer_id, zp, const.AnlageType.from_str(anlagetype)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/constants.py", line 72, in from_str
    raise NotImplementedError
NotImplementedError

**Comment by tschoerk** [comment]
The type of your anlage is probably something we haven't accounted for yet.

Please follow the steps under General Troubleshooting in the FAQs #19 
In the logs you can search for the entry "typ" under "anlage". Currently implemented are TAGSTROM, WAERMEPUMPE and BEZUG. Let us know what your type is and we can implement it.

**Comment by elmartinoAT** [comment]
I think NACHTSTROM

**Comment by DarwinsBuddy** [comment]
Next release will have NACHTSTROM support. Please create another issue if this doesn't resolve your issue. :+1:
