### ISSUE TITLE
Login Problem 

### ISSUE THREAD

**Issue by opb1978** [DarwinsBuddy/WienerNetzeSmartmeter#289]
I have done some debugging and also verified userid/pw for log.wien and this all works. I also disabled the Passkey stored in my log.wien account, so it only proposes password but still having the same issue:

Running Version 1.7.0 (but also tried with older versions)

I also tried configuring via configuration.yaml and this also did not help :-(

Logs from the Plugin

Logger: custom_components.wnsm.config_flow
Source: custom_components/wnsm/config_flow.py:50
integration: WienerNetzeSmartmeter ([documentation](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter), [issues](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues))
First occurred: 18:19:17 (1 occurrences)
Last logged: 18:19:17

Login failed. Check username/password.
Traceback (most recent call last):
  File "/config/custom_components/wnsm/config_flow.py", line 50, in async_step_user
    zps = await self.validate_auth(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
        user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/wnsm/config_flow.py", line 34, in validate_auth
    await self.hass.async_add_executor_job(smartmeter.login)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wnsm/api/client.py", line 157, in login
    code = self.credentials_login(url)
  File "/config/custom_components/wnsm/api/client.py", line 104, in credentials_login
    raise SmartmeterLoginError("Login failed. Check username/password.")
custom_components.wnsm.api.errors.SmartmeterLoginError: Login failed. Check username/password.

**Comment by webwude** [comment]
How many Zählpunkte do you have? The more the worst. 

I would recommend to reset everything and start from scratch.

**Comment by DarwinsBuddy** [comment]
A lot is broken currently on their side.
It's not just the login as it seems.

I try to get some information from my contacts, but can't promise anything right now.

In the meantime, we might have to wait for them to fix it, and check regularly https://smartmeter-web.wienernetze.at/verbrauchsdaten/grafische-darstellung

**Comment by W-M-B** [comment]
I am lucky still have daily updates..

![grafik](https://github.com/user-attachments/assets/25f38b35-8b40-46f5-a580-0f49813bfaee)

**Comment by l3rdy** [comment]
Everything works for me Perfectly again after the Maintenance they had on the 18th till 18:00

**Comment by sfbuch** [comment]
do you know, is there a similar solution for netze nö?

**Comment by DarwinsBuddy** [comment]
I just realized that they changed their T&Cs so you might just need to log in once manually and accept the changed terms. After that the integration might be good to re-login again :)

**Comment by DarwinsBuddy** [comment]
Re-opening this.
It seems that the capture is an additional blocker that appears out of nowhere every now and then.
Not even with a manual login it can be circumvented.
I'm reaching out to Wiener Stadtwerke for a potential talk about a collaboration.

**Comment by Favorita1100** [comment]
My solution: log in via browser once and accept the new agbs then credentials/ login works.

**Comment by W-M-B** [comment]
> My solution: log in via browser once and accept the new agbs then credentials/ login works.

This worked for me as well. Maybe this is an additional topic that can be solved by accepting the new T&C

**Comment by Moach2000** [comment]
Hi!
I also have some issues for weeks.
But to be sure - login is usually an email address. Correct?
BR

**Comment by fifistargate** [comment]
Same Problem, and yes username and password is correct:

wnsm: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 737, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/wnsm_sensor.py", line 88, in async_update
    await async_smartmeter.login()
  File "/config/custom_components/wnsm/AsyncSmartmeter.py", line 24, in login
    return await self.hass.async_add_executor_job(self.smartmeter.login)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wnsm/api/client.py", line 157, in login
    code = self.credentials_login(url)
  File "/config/custom_components/wnsm/api/client.py", line 104, in credentials_login
    raise SmartmeterLoginError("Login failed. Check username/password.")
custom_components.wnsm.api.errors.SmartmeterLoginError: Login failed. Check username/password.

**Comment by Moach2000** [comment]
In a nutshell what I did:
Login on the website with my login credentials. Accepted the new terms and conditions (or sth. similar). Did some clicks on the website to check out the changes (my last login was one year ago).
After that I deleted the integration in Hassio und tried to add it from scratch again (with success).

**Comment by fifistargate** [comment]
Still the same problem, even after accepting AGBs

**Comment by reox** [comment]
uhmm... now I got it the second time. I have the feeling they don't like the hourly or more logins :/

**Comment by schoeberlt** [comment]
Same issue here, login failed in home assistant three times today and received the e-mail three times

**Comment by reox** [comment]
Interestingly, my login does not fail. I think they are overhauling their login logic and thus sometimes the automatic logins are blocked...

**Comment by schoeberlt** [comment]
It‘s really strange, because apparently not all logins fail for me either, because somehow yesterday’s energy data got pulled. So it’s true that some but not all logins fail.

**Comment by mochitoju** [comment]
...same here (EMail)
Is it possible to reduce the logins (like two times a day) in config?

**Comment by W-M-B** [comment]
for me it works for now .., but I do get log.wien emails .. I like the idea @mochitoju  about having the options of data collection frequency. if it is possible to choose when/how often data is ingested from Wiener Netze Smartmeter Portal

**Comment by W-M-B** [comment]
hi, I had a look at log.wien to see if I can change something there.
I discovered a part called devicemanagement, that can be switched on/off.


![Image](https://github.com/user-attachments/assets/d851acb2-81e0-48a3-9d68-698d1afcb30c)

and possibility to be informed if someone out of Austria logs in:

![Image](https://github.com/user-attachments/assets/f2a3c4ac-867b-4218-b714-9ea05d1f0335)
Anyone has an idea what this will be about, maybe this is related to the email loggins?

**Comment by TheRealVira** [comment]
Ah so this is where all these „Anmeldeversuch“ E-Mail originated from.

**Comment by reox** [comment]
But they already stopped - and at the same time the login for HA fails now every time :/

**Comment by webwude** [comment]
I still get mails. Every two hours at the moment 🙄

**Comment by reox** [comment]
I think we need to investigate this issue more closely: #276

**Comment by akicker** [comment]
If I start the integation it works at the first run without errors- some of the next ones cause the errors 
therefore a question:
**How to modify the code, that the request is started only once a day?**
Maybe this could help to get yesterdays numbers errorless?

**Comment by DarwinsBuddy** [comment]
I changed the update interval from once per hour to once every 6 hours to reduce stress on the login service of wiener netze/wiener stadtwerke and thus potentially circumventing the login issue for now.

[1860b92](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/afc0f787d1366c0a8008e99a939bd547d1860b92)
still I'm hoping WienerStadtwerke will get back to my inquiry for meeting regarding this topic.
@W-M-B any news from your side?

**Comment by W-M-B** [comment]
no,  new

> I changed the update interval from once per hour to once every 6 hours to reduce stress on the login service of wiener netze/wiener stadtwerke and thus potentially circumventing the login issue for now.
> 
> [1860b92](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/afc0f787d1366c0a8008e99a939bd547d1860b92) still I'm hoping WienerStadtwerke will get back to my inquiry for meeting regarding this topic. [@W-M-B](https://github.com/W-M-B) any news from your side?

no news from my side .. I was skiing therefore I didnt follow up :-) .. will do now.

**Comment by W-M-B** [comment]
I stopped receiving the alerts from Logwien after 12. February.. I was on 1.6 then.
so maybe they reduced the rules for the login checker.
yesterday I upgraded to 1.71 looks nice 👍

**Comment by mundschenk-at** [comment]
I haven't gotten any mails even with the previous version (after acknowledging the new terms in the browser).

**Comment by reox** [comment]
> How do you get this diagram?

This is in the energy dashboard: https://my.home-assistant.io/redirect/energy/

**Comment by pujux** [comment]
I know it's been some time but as I just had a few problems first setting up the integration, it might be worth noting that you must not have MFA and a Passkey enabled on your log.wien account for the integration to be able to authenticate.

**Comment by DarwinsBuddy** [comment]
closing due to inactivity
