### ISSUE TITLE
Energy tab does not display any data

### ISSUE THREAD

**Issue by welcometopwn** [DarwinsBuddy/WienerNetzeSmartmeter#5]
Hello, i've installed and configured your integration yesterday but unfortunately i do not see any data displayed in the energy dashboard. Is there any extra steps i perhaps missed? The entity itself does contain some data/attributes.

The log file also returns some exceptions

```
Logger: homeassistant.helpers.entity
Source: custom_components/wnsm/api/client.py:38
Integration: WienerNetzeSmartmeter ([documentation](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter), [issues](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues))
First occurred: 3:55:50 PM (1 occurrences)
Last logged: 3:55:50 PM

Update for sensor.at0010000000000000001000004446232 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7be422c7f0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='log.wien', port=443): Max retries exceeded with url: /auth/realms/logwien/protocol/openid-connect/auth?client_id=wn-smartmeter&redirect_uri=https%3A%2F%2Fsmartmeter-web.wienernetze.at%2F&response_mode=fragment&response_type=code&scope=openid&nonce= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7be422c7f0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/wnsm/api/client.py", line 36, in login
    result = self.session.get(login_url)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='log.wien', port=443): Max retries exceeded with url: /auth/realms/logwien/protocol/openid-connect/auth?client_id=wn-smartmeter&redirect_uri=https%3A%2F%2Fsmartmeter-web.wienernetze.at%2F&response_mode=fragment&response_type=code&scope=openid&nonce= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7be422c7f0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/config/custom_components/wnsm/sensor.py", line 163, in async_update
    await self.hass.async_add_executor_job(smartmeter.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wnsm/api/client.py", line 38, in login
    raise SmartmeterConnectionError(f"Could not load login page. Error: {e}")
custom_components.wnsm.api.errors.SmartmeterConnectionError: Could not load login page. Error: HTTPSConnectionPool(host='log.wien', port=443): Max retries exceeded with url: /auth/realms/logwien/protocol/openid-connect/auth?client_id=wn-smartmeter&redirect_uri=https%3A%2F%2Fsmartmeter-web.wienernetze.at%2F&response_mode=fragment&response_type=code&scope=openid&nonce= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7be422c7f0>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by DarwinsBuddy** [comment]
I'm also not getting data since 20th of September. Maybe they had an outage on their API. I double checked, the api integration should work fine.

**Comment by DarwinsBuddy** [comment]
@welcometopwn I'd suggest to remove your exact meter id from the provided logs and put the (also in the future) in to a code block like this:

`this is code`

**Comment by DarwinsBuddy** [comment]
The way I read the errors is that the sensor tried to reach the API, couldn't succeed, tried it a couple of times more, got probably a HTTP 429 and exceeded the quota.

If you have been already able to fetch your data with that sensor, check your network settings.
If not, check your credentials if they are correct. They should be the same you're using when connecting to https://smartmeter-web.wienernetze.at

**Comment by welcometopwn** [comment]
Thanks for the heads up regarding the id. 

I do have some data now but it doesn't quite represent the data shown on the wienernetze website. I will keep an eye on that for a few days, perhaps they do have some issues on their end. My internet didn't had any outages around that time.

**Comment by DarwinsBuddy** [comment]
There is a lot of head room for improvement regarding compensating for the bad API of WN.

If you encounter problems don't hesitate to reopen that ticket or create another one (if it's a different issue).
