### ISSUE TITLE
Update of Sensor fails

### ISSUE THREAD

**Issue by hirschy81** [DarwinsBuddy/WienerNetzeSmartmeter#6]
Got the following Error message in the log file:

2022-09-23 08:50:39.778 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.at00100000000000000010000**XXXXXXXX** is taking over 10 seconds
2022-09-23 08:52:12.303 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.at00100000000000000010000**XXXXXXXX** fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 718, in async_device_update
    await task
  File "/config/custom_components/wnsm/sensor.py", line 164, in async_update
    zp = await self.get_zaehlpunkt(smartmeter)
  File "/config/custom_components/wnsm/sensor.py", line 120, in get_zaehlpunkt
    zp = [z for z in zps[0]["zaehlpunkte"] if z["zaehlpunktnummer"] == self.zaehlpunkt]
KeyError: 0

**Comment by DarwinsBuddy** [comment]
thanks :) seems like every now and then WN is not reliably returning any zaehlpunkte whatsoever.

Could you double check that you don't have a typo in your zaehlpunktnummer (if you configured the integration w/ `configuration.yaml`).
